init project

diff --git a/app/Dockerfile b/app/Dockerfile
--- a/app/Dockerfile
+++ b/app/Dockerfile
@@ -2,6 +2,7 @@ FROM python:3.10.12
 
 # Set the working directory
 WORKDIR /app
+
 # Copy application code
 COPY . .
 
@@ -11,6 +12,7 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
     curl \
     libgl1-mesa-glx \
     && rm -rf /var/lib/apt/lists/*
+
 # Configure pip to use a mirror if you download slow
 # RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
 #     pip3 config set global.trusted-host "pypi.tuna.tsinghua.edu.cn mirrors.pku.edu.cn" && \
@@ -27,6 +29,7 @@ ENV PATH="${POETRY_HOME}/bin:${PATH}"
 # RUN poetry self add poetry-plugin-pypi-mirror
 # ENV POETRY_PYPI_MIRROR_URL=https://mirrors.aliyun.com/pypi/simple/
 # ENV POETRY_PYPI_MIRROR_URL=https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
+
 # Configure Poetry to not create virtual environments
 RUN poetry config virtualenvs.create false
 
@@ -34,15 +37,27 @@ RUN poetry config virtualenvs.create false
 COPY pyproject.toml poetry.lock ./
 
 # Set the timeout for Poetry to 600 seconds
-ENV POETRY_INSTALLER_MAX_WORKERS=10
-ENV POETRY_HTTP_TIMEOUT=180
-# Install dependencies
-RUN poetry install --no-interaction --only main
+ENV POETRY_INSTALLER_MAX_WORKERS=1
+ENV POETRY_HTTP_TIMEOUT=600
+
+# Install dependencies with retry mechanism
+RUN pip install nvidia-cublas-cu12 --index-url https://pypi.org/simple
+RUN retry_count=0; \
+    until poetry install --no-interaction --only main; do \
+        if [ $retry_count -ge 3 ]; then \
+            echo "Failed to install dependencies after 3 attempts."; \
+            exit 1; \
+        fi; \
+        echo "Retrying dependency installation (attempt $((retry_count + 1)))..."; \
+        retry_count=$((retry_count + 1)); \
+        sleep 10; \
+    done
 
 RUN pip install --upgrade pip
 
 # Install Babel
 RUN pip install Babel
+
 # Compile translations
 RUN echo "Compiling translations..."
 RUN pybabel compile -d translations
@@ -55,6 +70,7 @@ RUN chmod +x ./start.sh
 
 # Expose port
 EXPOSE 8088
+
 # Run the application
 ENTRYPOINT ["./entrypoint.sh"]
 CMD ["./start.sh"]
